import sys
import os
from pathlib import Path
import logging
import networkx as nx

# Resolve paths
CURRENT_DIR = Path(__file__).resolve().parent
SCRIPTS_FA_DIR = CURRENT_DIR.parent
STREAM_DVFS_DIR = SCRIPTS_FA_DIR.parent
STREAM_WORKDIR = STREAM_DVFS_DIR.parent

sys.path.append(str(STREAM_WORKDIR))

from stream.stages.stage import Stage, MainStage
from stream.stages.parsing.accelerator_parser import AcceleratorParserStage
from stream.stages.parsing.onnx_model_parser import ONNXModelParserStage as StreamONNXModelParserStage
from stream.stages.generation.layer_stacks_generation import LayerStacksGenerationStage
from stream.stages.generation.tiling_generation import TilingGenerationStage
from stream.stages.generation.tiled_workload_generation import TiledWorkloadGenerationStage
from stream.workload.computation.computation_node import ComputationNode
from stream.workload.utils import visualize_computation_workload

# Configure logging to see the debug prints of the geometric propagation if needed
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class GeometricPropagationValidationStage(Stage):
    """
    Stage to validate that the Geometric Propagation generated a sound dependency graph.
    """
    def is_leaf(self) -> bool:
        return True

    def run(self):
        tiled_workload = self.kwargs["workload"]
        logger.info(f"Validating Tiled Workload generated by Geometric Propagation...")
        
        node_list = tiled_workload.node_list
        logger.info(f"Total Nodes: {len(node_list)}")
        
        # 1. Basic Connectivity Check
        # Every node except Source nodes should have predecessors.
        # Every node except Sink nodes should have successors.
        # This is a loose check, but good for catching complete failures.
        
        for node in node_list:
            preds = list(tiled_workload.predecessors(node))
            succs = list(tiled_workload.successors(node))
            
            # Simple heuristic: If it's a ComputationNode tiles, it usually needs inputs.
            # (Unless it's a primary input to the network, which we can't easily distinguish here without more context,
            # except checking input_names)
            
            # More specific check: Flash Attention Transpose Dependencies.
            # If we have a MatMul or Gemm downstream of a Transpose, we want to ensure edges exist.
        
        # 2. Check specific critical paths in Flash Attention
        # Look for Transpose nodes in the original graph (which are gone now, but their effect exists).
        # We look for Producer -> Consumer pairs where we know a Transpose was in between.
        # e.g. Q * K^T.
        
        # Verify Edges exist between layers.
        # Group by layer name
        nodes_by_layer = {}
        for node in node_list:
            base_name = node.name
            if base_name not in nodes_by_layer:
                nodes_by_layer[base_name] = []
            nodes_by_layer[base_name].append(node)
            
        logger.info(f"Layers found: {list(nodes_by_layer.keys())}")
        
        # In FA ONNX, we expect names like:
        # /MatMul (Q*K)
        # /Softmax
        # /MatMul_1 (Score * V)
        
        # Find keys that look like these.
        matmul_layers = [k for k in nodes_by_layer.keys() if "MatMul" in k or "Gemm" in k]
        logger.info(f"MatMul layers: {matmul_layers}")
        
        total_edges = tiled_workload.number_of_edges()
        logger.info(f"Total Edges in Tiled Graph: {total_edges}")
        
        if total_edges == 0:
            logger.error("FAILED: No edges generated! Geometric propagation failed completely.")
        else:
            logger.info("SUCCESS: Edges were generated.")
            
        # 3. Check for specific connectivity patterns
        # Identify producer/consumer pairs based on edges
        # Just print a few sample edges to verify they look sane (correct operands)
        sample_count = 0
        projection_layers = ["/q_proj", "/k_proj", "/v_proj", "/o_proj"]
        logger.info("Printing edges for projection layers:")
        
        for u, v, data in tiled_workload.edges(data=True):
             # Print if u or v contains one of the projection layer strings
             u_name = str(u.name)
             v_name = str(v.name)
             if any(proj in u_name for proj in projection_layers) or any(proj in v_name for proj in projection_layers):
                 logger.info(f"Edge: {u} -> {v}  | Operand: {data.get('operand')}")
        # 4. Visualize the graph
        output_dir = self.kwargs.get("output_dir", "outputs_test_geometric")
        vis_path = str(Path(output_dir) / "tiled_workload_geometric.png")
        logger.info(f"Visualizing graph to {vis_path}")
        try:
            visualize_computation_workload(tiled_workload, filepath=vis_path, cluster_by=None)
            logger.info("Visualization successful.")
        except Exception as e:
            logger.error(f"Visualization failed: {e}")

        yield tiled_workload, None

def run_test():
    # Parameters matching stream_dvfs_fa.py test code
    num_cores = 1
    seq_len = 32
    embedding_dim = 16
    tile_size = 16
    
    # Paths
    # Ensure these files exist or use generic ones
    workload_path = str(SCRIPTS_FA_DIR / "inputs" / "workloads" / f"FlashAttention_B=1_Seq={seq_len}_Embed={embedding_dim}_TileBr={tile_size}_TileBc={tile_size}_W8A8.onnx")
    accelerator_path = str(SCRIPTS_FA_DIR / "inputs" / "multicores" / f"FA_{num_cores}gemm_{num_cores}simd.yaml")
    mapping_path = str(SCRIPTS_FA_DIR / "inputs" / "mappings" / f"FA_{num_cores}gemm_{num_cores}simd_{seq_len//tile_size}tiles.yaml")
    
    output_dir = str(CURRENT_DIR / "outputs_test_geometric")
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    # Define the Stage pipeline
    parser_stage = StreamONNXModelParserStage
    accelerator_parser_stage = AcceleratorParserStage
    layer_stacks_generation_stage = LayerStacksGenerationStage
    tiling_generation_stage = TilingGenerationStage
    tiled_workload_generation_stage = TiledWorkloadGenerationStage
    validation_stage = GeometricPropagationValidationStage
    
    # Instantiate Main Stage
    mainstage = MainStage(
        [
            accelerator_parser_stage,
            parser_stage,
            layer_stacks_generation_stage,
            tiling_generation_stage,
            tiled_workload_generation_stage,
            validation_stage
        ],
        accelerator=accelerator_path,
        workload_path=workload_path,
        mapping_path=mapping_path,
        mode="fused",
        layer_stacks=[tuple(range(0, 1000))], # Single stack, similar to verify script
        loma_lpf_limit=6,
        nb_ga_individuals=4,
        nb_ga_generations=4,
        tiled_workload_path=f"{output_dir}/tiled_workload_test.pickle",
        dump_filename_pattern=f"{output_dir}/final_output",
        plot_hof=True,
        plot_file_name=f"{output_dir}/hof_plot",
        plot_per_core=True,
        output_dir=output_dir  # Pass output_dir to stages
    )
    
    # Run
    mainstage.run()

if __name__ == "__main__":
    run_test()
