
#  17   16
#  |    |
#  0 -- 1 -- 2 -- 3
#  |    |    |    |
#  4 -- 5 -- 6 -- 7
#  |    |    |    |
#  8 -- 9 --10 --11
#  |    |    |    |
# 12-- 13--14 --15


core_connectivity:
- bandwidth: 256
  cores:
  - 0
  - 1
  type: link
- bandwidth: 256
  cores:
  - 1
  - 2
  type: link
- bandwidth: 256
  cores:
  - 2
  - 3
  type: link

- bandwidth: 256
  cores:
  - 4
  - 5
  type: link
- bandwidth: 256
  cores:
  - 5
  - 6
  type: link
- bandwidth: 256
  cores:
  - 6
  - 7
  type: link

- bandwidth: 256
  cores:
  - 8
  - 9
  type: link
- bandwidth: 256
  cores:
  - 9
  - 10
  type: link
- bandwidth: 256
  cores:
  - 10
  - 11
  type: link

- bandwidth: 256
  cores:
  - 12
  - 13
  type: link
- bandwidth: 256
  cores:
  - 13
  - 14
  type: link
- bandwidth: 256
  cores:
  - 14
  - 15
  type: link

# vertical connections
- bandwidth: 256
  cores:
  - 0
  - 4
  type: link
- bandwidth: 256
  cores:
  - 1
  - 5
  type: link
- bandwidth: 256
  cores:
  - 2
  - 6
  type: link
- bandwidth: 256
  cores:
  - 3
  - 7
  type: link

- bandwidth: 256
  cores:
  - 4
  - 8
  type: link
- bandwidth: 256
  cores:
  - 5
  - 9
  type: link
- bandwidth: 256
  cores:
  - 6
  - 10
  type: link
- bandwidth: 256
  cores:
  - 7
  - 11
  type: link

- bandwidth: 256
  cores:
  - 8
  - 12
  type: link
- bandwidth: 256
  cores:
  - 9
  - 13
  type: link
- bandwidth: 256
  cores:
  - 10
  - 14
  type: link
- bandwidth: 256
  cores:
  - 11
  - 15
  type: link

# vector / offchip links
- bandwidth: 256
  cores:
  - 1
  - 16
  type: link
- bandwidth: 256
  cores:
  - 0
  - 17
  type: link

cores:
  0: stream_dvfs/config/cores/array_16x16.yaml
  1: stream_dvfs/config/cores/array_16x16.yaml
  2: stream_dvfs/config/cores/array_16x16.yaml
  3: stream_dvfs/config/cores/array_16x16.yaml
  4: stream_dvfs/config/cores/array_16x16.yaml
  5: stream_dvfs/config/cores/array_16x16.yaml
  6: stream_dvfs/config/cores/array_16x16.yaml
  7: stream_dvfs/config/cores/array_16x16.yaml
  8: stream_dvfs/config/cores/array_16x16.yaml
  9: stream_dvfs/config/cores/array_16x16.yaml
  10: stream_dvfs/config/cores/array_16x16.yaml
  11: stream_dvfs/config/cores/array_16x16.yaml
  12: stream_dvfs/config/cores/array_16x16.yaml
  13: stream_dvfs/config/cores/array_16x16.yaml
  14: stream_dvfs/config/cores/array_16x16.yaml
  15: stream_dvfs/config/cores/array_16x16.yaml
  16: stream_dvfs/config/cores/vec_64.yaml
  17: stream_dvfs/config/cores/offchip.yaml
name: FA_16gemm
offchip_core_id: 17
unit_energy_cost: 32 # 1pJ/B 1pJ*32B = 6.4pJ/256B
